### ISSUE TITLE
Add  setVisibility parameter to configureDT

### ISSUE THREAD

**Issue by rscher** [ODMDev/decision-center-api-samples#2]
**setVisibility** argument adds capability to set visible flag to true for all columns in DTs (only if set to false ) in  the branch.

proposed change for the customer might look like this-

java  -cp "<ODM_HOME>/teamserver/lib/*:<ODM_HOME>teamserver/lib/eclipse_plugins/*:" com.ibm.odm.tools.ConfigureDT -username username -password passwrd -url  URL 
  -dataSource jdbc/ilogDataSource  -decisionService decisionServiceName  -branch  branchName   -autoResize [true/false]  **-setVisibility [true/false]**

**Comment by alainrobert** [comment]
completed in v0.0.3
