### ISSUE TITLE
issue with configure-dt-0.0.3.jar .  unexpected argument -unhideColumns

### ISSUE THREAD

**Issue by rscher** [ODMDev/decision-center-api-samples#4]
issue with configure-dt-0.0.3.jar …

[root@zzxr7601 ~]#  /opt/IBM/ODM893/jdk/bin/java  -cp 
 “/opt/IBM/ODM893/teamserver/lib/*:/opt/IBM/ODM893/teamserver/lib/eclipse_plugins/*:” com.ibm.odm.tools.ConfigureDT -username rtsAdmin -password rtsAdmin -url http://zzxr7601.msci.svl.ibm.com:9084/decisioncenter   -dataSource jdbc/ilogDataSource  -decisionService  PremierDiscountRules_MainRuleFlow  -branch  OPR-MAIN   -autoResize false -unhideColumns true
 **unexpected argument -unhideColumns**
usage:
  java com.ibm.odm.tools.ConfigureDT -username username -password password -url url -dataSource dataSource -decisionService <dsName> [-overlapCheck true|false] [-gapCheck true|false] [-manualOrdering true|false] [-autoResize true|false] [-unhideColumns true]
        Update all decision tables properties according to option selected in the decision service selected
        If an option is not selected the property is not modified. At least one option must be selected

works without -unhideColumns arg

[root@zzxr7601 ~]# /opt/IBM/ODM893/jdk/bin/java  -cp “/opt/IBM/ODM893/teamserver/lib/*:/opt/IBM/ODM893/teamserver/lib/eclipse_plugins/*:” com.ibm.odm.tools.ConfigureDT -username rtsAdmin -password rtsAdmin -url http://zzxr7601.msci.svl.ibm.com:9084/decisioncenter   -dataSource jdbc/ilogDataSource  -decisionService  PremierDiscountRules_MainRuleFlow  -branch  OPR-MAIN   -autoResize false
Configure DT properties in decision service ‘PremierDiscountRules_MainRuleFlow’
Dec 03, 2021 5:26:26 PM com.ibm.rules.decisioncenter.remoting.internal.RemoteSessionHttpExecutorBuilder log
INFO: {“url”:“http://zzxr7601.msci.svl.ibm.com:9084/decisioncenter”,“datasource”:“jdbc/ilogDataSource”,“username”:“rtsAdmin”,“message”:“Sign in successfully”,“date”:“December 3, 2021 5:26:26 PM”}
Dec 03, 2021 5:26:26 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
..
..
[root@zzxr7601 ~]# find /opt/IBM -name configure-dt-*.jar
/opt/IBM/ODM893/teamserver/lib/configure-dt-0.0.3.jar

**Comment by alainrobert** [comment]
thanks for the report, I have updated the distribution to 0.0.4  to fix this issue.
