### ISSUE TITLE
Installing section still references configure-dt-0.0.4.jar, resulting in 404 error when clicking on it

### ISSUE THREAD

**Issue by rscher** [ODMDev/decision-center-api-samples#5]
https://github.com/ODMDev/decision-center-api-samples/tree/master/configureDT#installing
still has link for 0.0.4

**Installing**
Add the jar [configure-dt-0.0.4.jar ](https://github.com/ODMDev/decision-center-api-samples/raw/master/configureDT/configure-dt-0.0.4.jar)in teamserver/lib folder
 
which is a dead link resulting in 404 error.

Can you please update this to 0.0.5  ?
thanks
Russ

**Comment by alainrobert** [comment]
It is updated, thanks for your report
